IndoorPAHouse_MapScripts::
	.byte 0


IndoorPAHouse_TV::
# 5 "data/maps/IndoorPAHouse/scripts.pory"
	lock
# 6 "data/maps/IndoorPAHouse/scripts.pory"
	msgbox IndoorPAHouse_TV_Text_0, MSGBOX_SIGN
# 7 "data/maps/IndoorPAHouse/scripts.pory"
	waitmessage
# 8 "data/maps/IndoorPAHouse/scripts.pory"
	release
	end


IndoorPAHouse_TV_Text_0:
# 6 "data/maps/IndoorPAHouse/scripts.pory"
	.string "GIANT SCHLONG STEVE!!!\pDING!\p Steve is in disgust.$"
