PALake_Text_Pikachu:
	.string "CHU! \p"
	.string "Boutta shock these HFN's$"

PALake_Text_Pikachu_Cave:
	.string "You are now deserving...$"

PALake_Text_Pikachu_Cave_No_Items:
  .string "The power of Makeley awaits... \p"
  .string "But only to those deserving....$"

PALake_Text_Boy1:
	.string "Jumping off this cliff is fun!$"

PALake_Text_Girl1:
	.string "The ducks are so cute!$"

PALake_Secret_Cave_Text_1:
	.string "You hear the faint sounds of a \n"
	.string "studio audience.$"

PALake_Secret_Cave_Wall_Text: 
  .string "Do you choose this option?$"

PALake_Secret_Cave_Correct_Text:
  .string "Ding! That's the number one answer! \p"
  .string "Here is your prize!$"

PALake_Secret_Cave_Incorrect_Text:
  .string "That is the wrong option...$"


